### PR TITLE
feat!: adapt to yaru compact sizes

### PR DESCRIPTION
**Pull request by Feichtmeier**
WIP until we have yaru 1.0.0 for pubspec

- 34 pixel height icons
- 20 is the default icon size now which affects also listtiles and buttons ofc

See https://github.com/ubuntu/yaru.dart/pull/383

@Jupi007 should we export yaru.dart constants instead and use those? or do we want to play safe and just make sure we sync them?

### CODE REVIEW

**Comment by Jupi007** [comment]
> @Jupi007 should we export yaru.dart constants instead and use those? or do we want to play safe and just make sure we sync them?

We can export a restricted part of constants in a `public_constants.dart` file.

**Comment by Feichtmeier** [comment]
I don't mind :smile: what would you prefer

**Comment by Jupi007** [comment]
I would prefer to use constants from yaru.dart :)
But let's not export everything.

**Comment by Feichtmeier** [comment]
snapshot, this already looks like a very big improvement to me
grafik

**Review by Jupi007 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
