### PR TITLE
Example: fix touchpad/gesture scrolling on Wayland

### PR DESCRIPTION
**Pull request by jpnurmi**
https://github.com/flutter/flutter/pull/89944 introduced a new `PointerDeviceKind.trackpad` value.

Fixes: #287

### CODE REVIEW

**Comment by jpnurmi** [comment]
Wait, is the scroll configuration something that should be set from within `YaruCarousel` so that it works as desired in all apps out of the box?

**Comment by Jupi007** [comment]
Hmm, what do you mean exactly?

**Comment by jpnurmi** [comment]
By default, it's not possible to scroll list views and grid views etc. by press-and-drag with the mouse. The example had explicitly enabled that behavior by telling Flutter that mouse is a "drag scrolling" device too. I can see that this was done specifically for the carousel example, so I was wondering if we should do that in the carousel widget then. However, @Feichtmeier is proposing that we get rid of the whole mouse drag override.

**Comment by Jupi007** [comment]
Oh, okay.
Honestly, I think we should totally get rid of the mouse dragging in the carousel. This kind of behaviour is weird on the desktop. 
We already have many possibility of navigation in the carousel with the dots and the navigation buttons.

**Comment by jpnurmi** [comment]
Great, fully agreed! :)

**Comment by Feichtmeier** [comment]
> Oh, okay.
> Honestly, I think we should totally get rid of the mouse dragging in the carousel. This kind of behaviour is weird on the desktop. 
> We already have many possibility of navigation in the carousel with the dots and the navigation buttons.

But I like almost always use my trackpad for swiping pages in the carousel 🎠
You don't meant swiping right? Or do you? :(

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/195810254-ac97532a-f6c1-41c3-a2a8-6c11881b7620.mp4

**Review by Feichtmeier — APPROVED** [review]
Yes sorry I've forgotten this artefact!

**Comment by jpnurmi** [comment]
Swiping with a touchpad is fine and still works. Press and drag with a mouse no longer scrolls (as expected on desktop).

**Comment by Jupi007** [comment]
Yes, touchpad is fine :)
It is just the mouse dragging which is not something desired on the desktop.

**Pull request merged**
