### PR TITLE
Increase contrast of togglables unchecked border

### LINKED ISSUE #665: Increase contrast for checkbox border color
More context related to the discussion in the installer: https://github.com/canonical/ubuntu-desktop-installer/issues/1465

It would be great if we can update the checkbox colors for better color contrast and accessibility. After a discussion with @Jupi007 we proposed following border colors:

#959595 on light theme
#757575 on dark theme

Can we land this in Yaru widgets?

### PR DESCRIPTION
**Pull request by Jupi007**
|       | Before | After |
|-------|--------|-------|
| Light | Capture d’écran du 2023-03-09 14-28-52 | Capture d’écran du 2023-03-09 14-26-06 |
| Dark  | image | Capture d’écran du 2023-03-09 14-26-16 |

CC @elioqoshi @madsrh @jpnurmi 

Fixes #665

### CODE REVIEW

**Comment by madsrh** [comment]
Small adjustment, but this is better 👍 😄

**Review by Feichtmeier — APPROVED** [review]
LGTM

**Comment by jpnurmi** [comment]
@Jupi007 is this ready for merging?

**Comment by Jupi007** [comment]
Yes, I just wanted your green light, and also @elioqoshi one, but I suppose he agree this, so we can merge :)

**Comment by elioqoshi** [comment]
LGTM, thanks!

**Pull request merged**
