### PR TITLE
fix: add the missing optional icon parameters

### LINKED ISSUE #739: add the missing optional icon parameters
@Jupi007 @jpnurmi 

IMO we should remove the dependency to yaru icons
The amount of places where we use them is so low that I don't see why we just shouldn't add a required IconData or Icon parameter to these widgets:

grafik

Apart from making the dependency management easier across our apps and libs this would also make yaru widgets to be more opened to be used for example with adwaita icons or material icons

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #739

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@jpnurmi any veto for setting the branch protection rule "require 1 approval before merging"?

**Review by Jupi007 — APPROVED** [review]
LGTM 👍

**Comment by Jupi007** [comment]
Shouldn't we also add the icon properties to the theme classes ?

**Comment by Feichtmeier** [comment]
> Shouldn't we also add the icon properties to the theme classes ?

if you have material themes as blueprint no
there is no material theme that presets a prop to a certain Widget
only things like themes, sizes and colors

**Comment by Jupi007** [comment]
> if you have material themes as blueprint no
> there is no material theme that presets a prop to a certain Widget
> only things like themes, sizes and colors

Indeed, you're right.

**Pull request merged**
