### PR TITLE
Dialog update

### PR DESCRIPTION
**Pull request by Feichtmeier**
- extract the title to an individual widget
- add a YaruAlertDialog

### CODE REVIEW

**Comment by Jupi007** [comment]
Very nice idea to extract the dialog title :D

**Comment by Feichtmeier** [comment]
It was @jpnurmi idea :brain: :smile:

**Comment by Feichtmeier** [comment]
@Jupi007  could you check if you see any behavioral changes to the previous version which you introduced?

grafik
grafik

I also thought that the alert dialog should have a left aligned title - wdyt?

**Review by Jupi007 — APPROVED** [review]
LGFM :+1: 
I didn't see any regression on my side.
And the left aligned `Alert` title is also very nice :D

**Pull request merged**
