### PR TITLE
Add YaruCheckbox

### LINKED ISSUE #352: Add YaruCheckbox

### PR DESCRIPTION
**Pull request by Jupi007**
WIP, I will add screenshot later.

- [x] Add basic design
- [x] Add animations
- [x] Add/update golden test
- [x] Add functional test

Related to #202
Fixes #352

### CODE REVIEW

**Comment by Feichtmeier** [comment]
The CI fails because some dbus-XXX.deb artifact can't be installed in this ubuntu-latest CI container.
I "fixed" this by downgrading the containers to 22.04
https://github.com/ubuntu-flutter-community/software/pull/446/commits/e1798162e02ce5175262616c64546f846f9f8ee2
For flutter I can not see any negative side effects of this downgrading? @jpnurmi any veto?

**Comment by jpnurmi** [comment]
Moving the CI to 22.04 sounds fine. :+1: `ubuntu-latest` is still pointing to 20.04 which is apparently broken.
- https://github.com/actions/runner-images/issues/6488
- https://github.com/actions/runner-images/issues/6399

**Comment by Jupi007** [comment]
Here is a screencast:

https://user-images.githubusercontent.com/36476595/198849641-2d818862-6886-445c-bec6-a23e901f6091.mp4

**Comment by Jupi007** [comment]
Weird, the golden test fail here, but `flutter test --update-goldens` isn't creating any change locally 🤔

**Comment by Feichtmeier** [comment]
Wow that looks like a huge amount of work! Thank you

I think this looks great and the animations are also nice

The only part I am not convinced about is the form of the checkmark
Can't we leave it evenly formed?
I've noticed that most UI frameworks somehow aligned their checkmarks. Firefox, material and even vanilla framework where the un-even check mark in yaru gnome comes from, changed it back to the even stroked checkmark
grafik

**Comment by Jupi007** [comment]
> Wow that looks like a huge amount of work! Thank you
>
> I think this looks great and the animations are also nice

Thanks a lot 😃
I brained a long time how to implement all this.
I hesitated between reuse some parts of material tooglable class stuff, and redo everything in another way.
And I finally choose the last solution, because like this we will be totally decoupled from their design, and so any material change won't affect us! This also mean, no dirty patch, etc.

> The only part I am not convinced about is the form of the checkmark
> Can't we leave it evenly formed?

Capture d’écran du 2022-10-29 23-23-13

Like this? 🙃
Honestly, after thinking about it, I think you're maybe right 🥲
But I did an adjusted checkmark, it is very sight, but it is not the same as the material one!

**Comment by madsrh** [comment]
This looks great @Jupi007 and very slick animations 😎

**Comment by Jupi007** [comment]
Thanks @madsrh 😃

**Comment by Feichtmeier** [comment]
Hm, merging main should actually also pull in the changes to the CI to use ubuntu-22-04 instead ubuntu-latest which fixes the issue with this dbus.deb 
Wonder why this doesn't happen

**Comment by Jupi007** [comment]
Hmm, both main and this branch are still using ubuntu-latest :)

**Comment by Feichtmeier** [comment]
Check out locally animations are really :+1: nice

Just one question, is the size change intended?
grafik

I am not against or pro just wanted to be sure this does not have any negative side effects when we exchange material checkboxes with yarucheckboxes in "all" our apps : D

**Comment by Jupi007** [comment]
There should be no problem :)

https://user-images.githubusercontent.com/36476595/198971099-89244ac8-dec4-49c0-90d2-536be8014491.mp4

The material checkbox got a transparent activable padding, the yaru one also have one, but smaller 😉

**Pull request merged**
