### PR TITLE
Improve popupmenubutton style consistency

### PR DESCRIPTION
**Pull request by whiskeyPeak**
This PR matches the border radius and colour of the popupbutton to the popupmenu.

## Pull request checklist

- [x] This PR does not introduce visual changes, **or**
  - I ran `flutter test --update-goldens` and committed the changes if there were any, **or**
  - I added before/after/light/dark screenshots if the visual changes I made were not covered by golden tests.
    | |Before|After|
    |-|-|-|
    |Light|Screenshot from 2023-01-09 23-40-51 | Screenshot from 2023-01-09 23-40-07|
    |Dark| Screenshot from 2023-01-09 23-50-59| Screenshot from 2023-01-09 23-50-06|

### CODE REVIEW

**Comment by whiskeyPeak** [comment]
I tried to expose the ```shape``` property as well, but because ```Theme.of(context)``` can't be const, that wasn't possible.

**Comment by Feichtmeier** [comment]
hmmm do we want all popup menus to have this border radius? then this is a change for yaru.dart
or do we only want this for this specific "fake dropdowns" ?

CC @jpnurmi @Jupi007

**Comment by Jupi007** [comment]
Imo, this should be applied to all popup menus.

**Comment by Feichtmeier** [comment]
> Imo, this should be applied to all popup menus.

Then we should change this in yaru.dart and if I am not wrong this change is then no longer needer :thinking:

**Comment by Jupi007** [comment]
> Then we should change this in yaru.dart and if I am not wrong this change is then no longer needer thinking

This is also my opinion.

**Comment by whiskeyPeak** [comment]
Sounds good! I'll open up a PR over there then.

**Comment by Feichtmeier** [comment]
@whiskeyPeak thank you!

While you are at it, could you instead of changing the border to match the button border change the button border to match the outlined button border? =) Wanted to do this today but since you are on it would be nice

**Comment by whiskeyPeak** [comment]
> @whiskeyPeak thank you!
> 
> While you are at it, could you instead of changing the border to match the button border change the button border to match the outlined button border? =) Wanted to do this today but since you are on it would be nice

The problem with that is that every other yaru widget uses the same border colour as the button border. ie: YaruOptionButtons, YaruSection, YaruBanner, YaruCarousel...
So if we want to change the border colour of the PopupMenuButton, it would probably be best if we do it via modifying the constant.

**Pull request closed without merging**
