### PR TITLE
Golden YaruIconButton test

### PR DESCRIPTION
**Pull request by jpnurmi**
This test catches unintentional visual changes. Whenever pushing intentional visual changes, one would have to update the golden images by running:
```
flutter test --update-goldens
```
P.S. GitHub shows the before and after images side by side in the PR diff. :wink:

### CODE REVIEW

**Comment by Jupi007** [comment]
Ohhh, awesome! 😮

**Comment by jpnurmi** [comment]
For example, the second commit that adds missing disabled state handling for YaruIconButton:
image

**Comment by jpnurmi** [comment]
It's tempting to put the tests in `test/goldens` but Flutter tests are normally run with a special test font whereas these golden tests require us to load real fonts.

**Review by Feichtmeier — APPROVED** [review]

**Review by Jupi007 — COMMENTED** [review]
Sorry, I outside under my car, so I didn't see the review request :)

Looks good for me.
This is a really nice feature!

**Pull request merged**
