### PR TITLE
add NavigationPage

### PR DESCRIPTION
**Pull request by d-loose**
https://user-images.githubusercontent.com/113362648/211363557-12af5c03-35bf-462d-9b08-c4c7d44551b9.mp4

I'll add some widget tests in a separate PR

## Pull request checklist

- [x] This PR does not introduce visual changes, **or**
  - I ran `flutter test --update-goldens` and committed the changes if there were any, **or**
  - I added before/after/light/dark screenshots if the visual changes I made were not covered by golden tests.
    | |Before|After|
    |-|-|-|
    |Light| | |
    |Dark| | |

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you @d-loose 

Just for the sake of consistency, could use YaruBackButton for the leading widget?

**Comment by jpnurmi** [comment]
Sorry, I can't help myself but there's something inconsistent that stands out :D

image

**Comment by d-loose** [comment]
Naming things is certainly not one of my strengths :laughing: 
`YaruNavigationPage` is an actual widget though - this page showcases the navigation in both `YaruNavigationPage` and `YaruMasterDetailPage`, depending on the "compact mode" setting. I wouldn't mind calling it `YaruNavigationPage` though.

**Comment by Feichtmeier** [comment]
:shrug: yeah just change it xD For a moment I thought you mean NaviGationPage to match the camel case line xD

**Comment by jpnurmi** [comment]
Or maybe we could call it `YaruBackButton` :)

**Comment by Feichtmeier** [comment]
The GitHub cloud ☁️ helpers have a bad day.  Container for the flutter snap test always hangs. Restarting

**Pull request merged**
