### PR TITLE
Better PULL_REQUEST_TEMPLATE

### PR DESCRIPTION
**Pull request by Jupi007**
Improve the PR template with a table.
The checklist is problematic because it add an undesired todo list to the PR.

I saw that kind of table in many other repo like this one:
https://github.com/sulu/sulu/blob/2.5/.github/PULL_REQUEST_TEMPLATE.md

In the future we could add more questions.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
One mistake I sometimes do is to forget that changes in deps might also change goldens. Eventually you could include this

**Comment by jpnurmi** [comment]
What if we'd put the instructions in a comment?

**Comment by jpnurmi** [comment]
I can extend the CI to:
- add PR comment if golden changes detected
- run golden tests nightly and automatically open a PR if there are changes

**Comment by Jupi007** [comment]
The CI solution is always the most elegant one 👍
But we should at least show a comment for the case there's some not covered style change.

**Comment by jpnurmi** [comment]
I was thinking that we could keep the existing info but just make it a comment to avoid core contributors needing to repeatedly delete cruft. :)

```
<!--
## PULL REQUEST CHECKLIST

If this PR introduces visual changes:
- Run `flutter test --update-goldens` and commit the changes if there were any, **or**
- Uncomment the table below and attach before/after/light/dark screenshots if the visual changes were not covered by golden tests.
-->

<!--
| |Before|After|
|-|-|-|
|Light| | |
|Dark| | |
-->
```

**Comment by Jupi007** [comment]
This was exactly what I thinking of :)

@Feichtmeier what do you think of?

**Comment by jpnurmi** [comment]
```
<!-- REMINDER: run `flutter test --update-goldens` or attach screenshots below, please

|       | Before | After |
|-------|--------|-------|
| Light |        |       |
| Dark  |        |       |
-->
```

**Comment by jpnurmi** [comment]
And if a golden test fails in the CI, we could post an automated PR comment:

> The following golden image(s) may be out of date. Did you forget to run `flutter test --update-goldens`?
> - test/foo/goldens/bar.png
> - test/foo/goldens/qux.png

**Comment by Jupi007** [comment]
Template comment + CI looks good for me :)
I'll close this PR, so you can create a new one.

**Comment by jpnurmi** [comment]
Feel free to update this if you like the proposal. I need to take care of some practicalities but I'm available to +1. :)

**Comment by Jupi007** [comment]
I'll update this PR with your second to last proposal.
In fact I like the latest one, but if somebody who doesn't know well this repo want to contribute, it could be confusing for him.

I leave you the CI golden commenting part :D

**Pull request closed without merging**
