### PR TITLE
fix(YaruWindowControl): radius, color, padding 

### PR DESCRIPTION
**Pull request by Feichtmeier**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@Jupi007 any idea why this error occurs?

/opt/hostedtoolcache/flutter/stable-3.16.3-x64/.pub-cache/hosted/pub.dev/golden_toolkit-0.13.0/lib/src/widget_tester_extensions.dart:63:17: Error: The method 'clearTextScaleFactorTestValue' isn't defined for the class 'TestWindow'.
 - 'TestWindow' is from 'package:flutter_test/src/window.dart' ('/opt/hostedtoolcache/flutter/stable-3.16.3-x64/packages/flutter_test/lib/src/window.dart').
Try correcting the name to the name of an existing method, or defining a method named 'clearTextScaleFactorTestValue'.
    this.window.clearTextScaleFactorTestValue();
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
❌ loading /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/foundation/yaru_border_radius_test.dart (failed)
  Failed to load "/home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/foundation/yaru_border_radius_test.dart": Compilation failed for testPath=/home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/foundation/yaru_border_radius_test.dart

do we also need to pump the golden version?

**Comment by Feichtmeier** [comment]
Weird, after updating golden version and building goldens again the test passes locally
grafik

**Comment by Jupi007** [comment]
@Feichtmeier Maybe should you do a first PR to update the goldens, then a second related to `YaruWindowControl`.
So we can clearly see the change you did in the golden diff.

And is your problem a local one? 🤔
Did you tried to clear your dependencies?

**Comment by Feichtmeier** [comment]
locally the tests pass now
but since I updated the versions the issues are only with the close button in the light theme now, basically the part I have changed here
for some reason only on github

**Pull request closed without merging**
