### PR TITLE
Add YaruBackButtonTheme & YaruBackButtonStyle (rounded vs. square)

### PR DESCRIPTION
**Pull request by jpnurmi**
| Square | Rounded |
|---|---|
| Screenshot from 2023-01-15 23-12-35 | Screenshot from 2023-01-15 23-12-22 |

### CODE REVIEW

**Comment by Feichtmeier** [comment]
That's nice! It's just a little bit too big IMO

**Comment by jpnurmi** [comment]
YaruBackButton uses a YaruIconButton that already has a fixed 40x40 size.

https://github.com/ubuntu/yaru_widgets.dart/blob/8010f16248fbb1e4ee0479da7994b67e4d92ad65/lib/src/controls/yaru_icon_button.dart#L12

https://github.com/ubuntu/yaru_widgets.dart/blob/8010f16248fbb1e4ee0479da7994b67e4d92ad65/lib/src/controls/yaru_icon_button.dart#L45

**Comment by Feichtmeier** [comment]
> YaruBackButton uses a YaruIconButton that already has a fixed 40x40 size.
> 
> https://github.com/ubuntu/yaru_widgets.dart/blob/8010f16248fbb1e4ee0479da7994b67e4d92ad65/lib/src/controls/yaru_icon_button.dart#L12
> 
> https://github.com/ubuntu/yaru_widgets.dart/blob/8010f16248fbb1e4ee0479da7994b67e4d92ad65/lib/src/controls/yaru_icon_button.dart#L45

Woops, right, but I think "Center" is what really forces it to not expand anymore. Could we put this here aswell or is this weird?

**Comment by jpnurmi** [comment]
Center forces it a bit smaller but depending on the context, I think it's still too large...

image

**Comment by jpnurmi** [comment]
Using `YaruIconButton` directly to be able to customize:
```dart
YaruIconButton(
  iconSize: 32,
  padding: EdgeInsets.zero,
  onPressed: Wizard.of(context).back,
  icon: const Icon(YaruIcons.go_previous),
)
```
image

**Comment by Feichtmeier** [comment]
> 

IMO that's a good size :+1: 
but let's ask the others @Jupi007 @madsrh

**Comment by Jupi007** [comment]
LGFM 👍

**Comment by jpnurmi** [comment]
[Screencast from 2023-01-19 14-43-34.webm](https://user-images.githubusercontent.com/140617/213458656-c5cea56c-16a3-4f35-b3dc-01379e821362.webm)

**Pull request merged**
