### PR TITLE
YaruWindowControl: add subtle outline for high-contrast themes

### PR DESCRIPTION
**Pull request by jpnurmi**
The outline is not really noticeable except with high-contrast themes to make the window controls stand out for accessibility reasons.

|   | Before | After |
|---|--------|-------|
| Light HC (experimental) | image | image |
| Dark HC (experimental) | image | image |
| Light | image | image |
| Dark | image | image |

Ref: ubuntu/yaru.dart#305

### CODE REVIEW

**Comment by jpnurmi** [comment]
GCC for reference:

| Light | Dark |
|---|---|
| image | image |

**Comment by Feichtmeier** [comment]
Holy moly, 😂
You had me a little scared with "not really noticeable". But they are not noticeable as far as I can see which is the only possible way to merge this for normal themes. Can anyone see anything?!?

**Comment by jpnurmi** [comment]
I was like "he's gonna murder me" if I even propose an outline so I was relieved I couldn't see it with my bare eyes with the normal themes. :D

**Comment by jpnurmi** [comment]
Actually, one can notice it when disabled. The screenshot is not ideal though because it's taken against a white background.

image

**Comment by jpnurmi** [comment]
Here's with minimize & maximize disabled:

| Light | Dark |
|---|---|
| image | image |

**Comment by Feichtmeier** [comment]
Hm can you make this improvement on high contrast without affecting the other themes? Our gnome window controls also have no outline, regarding of enabled/disabled

**Comment by Jupi007** [comment]
I agree, there's shouldn't be any outline in default theme.

But it is a great idea for the HC mode 👍

**Pull request closed without merging**
