### PR TITLE
Add YaruBorderContainer

### PR DESCRIPTION
**Pull request by jpnurmi**
This is sort of a fusion the software app's BorderContainer and the installer's RoundedContainer.

NOTE: Unlike the software app's BorderContainer, this does not add padding by default because most containers in the installer are not padded.

P.S. Golden tests in various configurations are included, see screenshots in the "Files changed" tab.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
grafik

Cool!

Do you plan to use it for the section, banner, etc ?

I think eventually the slightly softer border is better for the border here:
Theme.of(context).colorScheme.onSurface.withOpacity(0.03)

**Comment by jpnurmi** [comment]
> Do you plan to use it for the section, banner, etc ?

Sure thing :+1: 

> I think eventually the slightly softer border is better for the border here:
> Theme.of(context).colorScheme.onSurface.withOpacity(0.03)

I copied the background from the software and it was already using this exact same value as the background color. Do we need any default background color at all for the generic YaruBorderContainer or could that be something set in the software app?

**Comment by jpnurmi** [comment]
In general, which lines should use the common divider color, and which should be softer?

Can we somehow unify these?

```sh
yaru.dart (main)$ git grep onSurface.withOpacity
lib/src/themes/common_themes.dart:      bottom: BorderSide(color: colorScheme.onSurface.withOpacity(0.2)),
lib/src/themes/common_themes.dart:      bottom: BorderSide(color: colorScheme.onSurface.withOpacity(0.2)),
lib/src/themes/common_themes.dart:    dividerColor: colorScheme.onSurface.withOpacity(0.12),
lib/src/themes/common_themes.dart:      unselectedItemColor: colorScheme.onSurface.withOpacity(0.8),
lib/src/themes/common_themes.dart:    dividerColor: colorScheme.onSurface.withOpacity(0.12),
```
```sh
yaru_widgets.dart (border-container)$ git grep onSurface.withOpacity
example/lib/pages/carousel_page.dart:            color: Theme.of(context).colorScheme.onSurface.withOpacity(0.1),
example/lib/pages/draggable_page.dart:        color: Theme.of(context).colorScheme.onSurface.withOpacity(.1),
lib/src/controls/yaru_icon_button.dart:          return colors.onSurface.withOpacity(0.38);
lib/src/controls/yaru_icon_button.dart:        return colors.onSurface.withOpacity(0.8);
lib/src/controls/yaru_icon_button.dart:          return colors.onSurface.withOpacity(0.1);
lib/src/controls/yaru_icon_button.dart:            return colors.onSurface.withOpacity(0.12);
lib/src/controls/yaru_icon_button.dart:            return colors.onSurface.withOpacity(0.08);
lib/src/controls/yaru_icon_button.dart:            return colors.onSurface.withOpacity(0.12);
lib/src/controls/yaru_popup_menu_button.dart:    final borderColor = Theme.of(context).colorScheme.onSurface.withOpacity(
lib/src/layouts/yaru_master_tile.dart:              ? Theme.of(context).colorScheme.onSurface.withOpacity(0.07)
lib/src/layouts/yaru_master_tile.dart:          iconColor: Theme.of(context).colorScheme.onSurface.withOpacity(0.8),
lib/src/layouts/yaru_navigation_rail_item.dart:            ? Theme.of(context).colorScheme.onSurface.withOpacity(.1)
lib/src/pages/yaru_section.dart:              color: Theme.of(context).colorScheme.onSurface.withOpacity(0.15),
lib/src/pages/yaru_tabbed_page.dart:                color: Theme.of(context).colorScheme.onSurface.withOpacity(0.1),
lib/src/utilities/yaru_banner.dart:        : Theme.of(context).colorScheme.onSurface.withOpacity(0.01);
lib/src/utilities/yaru_banner.dart:        hoverColor: Theme.of(context).colorScheme.onSurface.withOpacity(0.1),
lib/src/utilities/yaru_border_container.dart:            : theme.colorScheme.onSurface.withOpacity(0.03));
lib/src/utilities/yaru_carousel.dart:                    : Theme.of(context).colorScheme.onSurface.withOpacity(.3),
```

**Comment by jpnurmi** [comment]
For example, could we get away with just two variants?

| Color | Value | Context |
|---|---|---|
| `DividerTheme.color` | `ColorScheme.onSurface.withOpacity(0.12)` | A stronger variant used by the `Divider` and `VerticalDivider` widgets |
| `ThemeData.dividerColor` | `ColorScheme.onSurface.withOpacity(0.03)` | A softer variant used for rounded containers, sections, banners etc. |

**Comment by jpnurmi** [comment]
| `Theme.dividerColor` | `ColorScheme.onSurface.withOpacity(0.03)` |
|---|---|
| yaru_border_container-padding-margin-light | yaru_border_container-padding-margin-light |
| yaru_border_container-padding-margin-dark | yaru_border_container-padding-margin-dark |
| yaru_border_container-padding-margin-clip-light | yaru_border_container-padding-margin-clip-light |
| yaru_border_container-padding-margin-clip-dark | yaru_border_container-padding-margin-clip-dark |
| yaru_border_container-padding-light | yaru_border_container-padding-light |
| yaru_border_container-padding-dark | yaru_border_container-padding-dark |
| yaru_border_container-padding-clip-light | yaru_border_container-padding-clip-light |
| yaru_border_container-padding-clip-dark | yaru_border_container-padding-clip-dark |
| yaru_border_container-margin-light | yaru_border_container-margin-light |
| yaru_border_container-margin-dark | yaru_border_container-margin-dark |
| yaru_border_container-margin-clip-light | yaru_border_container-margin-clip-light |
| yaru_border_container-margin-clip-dark | yaru_border_container-margin-clip-dark |
| yaru_border_container-default-light | yaru_border_container-default-light |
| yaru_border_container-default-dark | yaru_border_container-default-dark |
| yaru_border_container-custom-light | yaru_border_container-custom-light |
| yaru_border_container-custom-dark | yaru_border_container-custom-dark |
| yaru_border_container-clip-light | yaru_border_container-clip-light |
| yaru_border_container-clip-dark | yaru_border_container-clip-dark |

**Comment by Feichtmeier** [comment]
Ok 👌
Then let's keep both
But default to divider colour for the border container
I can then insert the lighter border for the banners
In a grid full of banners the stronger border becomes too strong but for things like context menus maybe even divider colour is too light
I need to check it live but you can merge this anyways and we can see where we need what stroke strength after

**Comment by jpnurmi** [comment]
Ok, I switched it back to `DividerTheme.color`! Is it ok to keep `Theme.dividerColor` as a fallback because `DividerTheme.color` is nullable?

**Pull request merged**
