### PR TITLE
Release 2.0.0-beta

### PR DESCRIPTION
**Pull request by Feichtmeier**
# 2.0.0

- [Paul Kepinski](https://github.com/Jupi007): Add YaruRadio (#360)
- [Paul Kepinski](https://github.com/d-loose): Master detail controller (#358)
- [Paul Kepinski](https://github.com/Jupi007): Decrease YaruTitleBar height (#357)
- [Paul Kepinski](https://github.com/Jupi007): Add YaruCheckbox (#351)
- [Paul Kepinski](https://github.com/Jupi007): Use ubuntu 22.04 for build task (#355)
- [Paul Kepinski](https://github.com/gumbarros): Showcase all YaruValues of the enum instead of the hard-coded list. (#350)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Update readme (#349)
- [J-P Nurmi](https://github.com/jpnurmi): README.md: remove old Yaru*Row and YaruPage references (#347)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCarousel: allow creating without controller (#345)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCheckButton: add golden test variants for tristate (#344)
- [Paul Kepinski](https://github.com/Jupi007): Example: update nav icons (#348)
- [Paul Kepinski](https://github.com/Jupi007): _YaruCheckedPopupMenuItemState: show changing state (#346)
- [Paul Kepinski](https://github.com/Jupi007): YaruPopupMenuButton improvements (#343)
- [Paul Kepinski](https://github.com/Jupi007): YaruCheckButton throw an exception with tristate (#342)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): CarousselController: do not dispose (#340)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCheckedPopupMenuItem: add golden test (#337)
- [J-P Nurmi](https://github.com/jpnurmi): Update PR template (#338)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCompactLayout: add golden test (#336)
- [J-P Nurmi](https://github.com/jpnurmi): Add YaruBorderContainer (#333)
- [J-P Nurmi](https://github.com/jpnurmi): Introduce YaruSwitchButton (#335)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterDetailPage: add golden test (#327)
- [J-P Nurmi](https://github.com/jpnurmi): Force-upgrade yaru.dart to v0.4.3 (#332)
- [J-P Nurmi](https://github.com/jpnurmi): Update .gitignore & .metadata (#331)
- [J-P Nurmi](https://github.com/jpnurmi): YaruRadioButton: add golden test (#330)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCheckButton: add golden test (#329)
- [J-P Nurmi](https://github.com/jpnurmi): rm -rf linux/ (#328)
- [J-P Nurmi](https://github.com/jpnurmi): Templatize YaruGoldenVariant (#326)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCloseButton: add golden test (#324)
- [J-P Nurmi](https://github.com/jpnurmi): YaruBackButton: add golden test (#323)
- [J-P Nurmi](https://github.com/jpnurmi): YaruOptionButton: add golden test (#322)
- [J-P Nurmi](https://github.com/jpnurmi): YaruXxxProgressIndicator: add golden test (#325)
- [J-P Nurmi](https://github.com/jpnurmi): Golden YaruIconButton test (#294)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Example: clean up popup page (#321)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): YaruPopupMenuButton: add multi check item (#319)
- [J-P Nurmi](https://github.com/jpnurmi): Remove UbuntuLogo (#318)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): MultiSelect (#313)
- [J-P Nurmi](https://github.com/jpnurmi): Document and clean up the constants (#316)
- [J-P Nurmi](https://github.com/jpnurmi): Docs: remove old YaruPageItem references (#315)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Popup: no initial value (#314)
- [J-P Nurmi](https://github.com/jpnurmi): Master-detail: update docs & add screenshots (#312)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): YaruPopupMenuButton: use builder and improve (#311)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Add YaruPopupMenuButton (#310)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): YaruBanner: add iconpadding (#308)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Improve YaruBanner (#307)
- [J-P Nurmi](https://github.com/jpnurmi): Yaru~~Dialog~~TitleBar: add support for leading & trailing widgets (#298)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Pubspec: Bump yaru version for appbar change (#304)
- [J-P Nurmi](https://github.com/jpnurmi): Fix use of deprecated members (#303)
- [J-P Nurmi](https://github.com/jpnurmi): Enable use_super_parameters (#301)
- [J-P Nurmi](https://github.com/jpnurmi): YaruIconButton: handle disabled state (#299)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCheckButton & YaruRadioButton: add missing behavioral properties (#295)
- [J-P Nurmi](https://github.com/jpnurmi): Example: fix touchpad/gesture scrolling on Wayland (#302)
- [Paul Kepinski](https://github.com/Jupi007): LandscapeLayout: fix resize indicator color (#300)
- [Paul Kepinski](https://github.com/Jupi007): YaruCompactLayout: use thinner scrollbar (#297)
- [Paul Kepinski](https://github.com/Jupi007): YaruNavigationRailItem: add tooltip (#296)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): DialogTitle: don't hide 🫥 properties with strings (#286)
- [Paul Kepinski](https://github.com/Jupi007): Move layouts in /src (#293)
- [Paul Kepinski](https://github.com/Jupi007): Replace all Material icons with Yaru ones (#292)
- [J-P Nurmi](https://github.com/jpnurmi): Import CheckButton & RadioButton from ubuntu-flutter-plugins/ubuntu_widgets (#291)
- [Paul Kepinski](https://github.com/Jupi007): Re-add tab background (#290)
- [Paul Kepinski](https://github.com/Jupi007): Move layouts in /src (#293)
- [Paul Kepinski](https://github.com/Jupi007): Replace all Material icons with Yaru ones (#292)
- [J-P Nurmi](https://github.com/jpnurmi): Import CheckButton & RadioButton from ubuntu-flutter-plugins/ubuntu_widgets (#291)
- [Paul Kepinski](https://github.com/Jupi007): Re-add tab background (#290)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Remove YaruAlertDialg and YaruSimpleDialog (#285)
- [J-P Nurmi](https://github.com/jpnurmi): Remove YaruPageItemTitle (#273)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCompactLayout: replace icon/titleBuilder with itemBuilder (#284)
- [Paul Kepinski](https://github.com/Jupi007): YaruLandscapeLayout: use DividerTheme (#283)
- [Paul Kepinski](https://github.com/d-loose): set separate color for subtitle in YaruMasterTile (#281)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterDetailPage: remove unused titleBuilder (#279)
- [Paul Kepinski](https://github.com/Jupi007): Layouts: better rtl support (#282)
- [Paul Kepinski](https://github.com/Jupi007): YaruLandscapeLayout: allow left pane resizing (#266)
- [Paul Kepinski](https://github.com/Jupi007): MaterDetails: add tiny selected tile background animation (#278)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterListView: create only one scroll controller (#276)
- [J-P Nurmi](https://github.com/jpnurmi): Add initial YaryCompactLayoutTheme (#275)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCompactLayout: remove superfluous sized box (#274)
- [Paul Kepinski](https://github.com/d-loose): unify YaruIconButton and YaruRoundToggleButton (#264)
- [J-P Nurmi](https://github.com/jpnurmi): Rename YaruPageItemListView to YaruMasterListView (#272)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Add PR template (#270)
- [J-P Nurmi](https://github.com/jpnurmi): Yaru master detail theme (#265)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): YaruBanner: fix text style regression (#268)
- [Paul Kepinski](https://github.com/d-loose): Use widgets as parameters in Yaru[Section,TabbedPage,Banner] (#262)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterDetailPage: remove built-in app bar in favor of YaruDetailPage (#263)
- [J-P Nurmi](https://github.com/jpnurmi): Add YaruBackButton (#260)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterDetailPage: add tile builder (#252)
- [J-P Nurmi](https://github.com/jpnurmi): Example: center the toggle button to avoid stretching it (#258)
- [J-P Nurmi](https://github.com/jpnurmi): YaruPortraitLayout: expand pages to available size (#254)
- [J-P Nurmi](https://github.com/jpnurmi): YaruPortraitLayout: remove the FAB (#253)
- [J-P Nurmi](https://github.com/jpnurmi): Remove YaruPageItem (#251)
- [J-P Nurmi](https://github.com/jpnurmi): MasterDetailPage: replace "page item" with indexed builders (#248)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCompactLayout: replace "page item" with indexed builders (#250)
- [J-P Nurmi](https://github.com/jpnurmi): YaruCompactLayout: add onSelected callback (#249)
- [J-P Nurmi](https://github.com/jpnurmi): YaruMasterDetailPage: allow managing the page index (#247)
- [J-P Nurmi](https://github.com/jpnurmi): Example: fix alphabetical order (#246)
- [J-P Nurmi](https://github.com/jpnurmi): Remove YaruPage in favor of the padding etc. constants (#244)
- [Paul Kepinski](https://github.com/Jupi007): Use animation in YaruSelectableContainer (#245)
- [Paul Kepinski](https://github.com/Jupi007): Replace NavigationRail with YaruNavigationRail (#201)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): YaruPageItem: add more flexibility (#242)
- [J-P Nurmi](https://github.com/jpnurmi): Example: standalone pages in alphabetical order (#241)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Analysis improvements and fixes (#240)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Split the CI (#239)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Remove yaru search app bar (#238)
- [J-P Nurmi](https://github.com/jpnurmi): Remove Yaru*Row widges (#237)
- [J-P Nurmi](https://github.com/jpnurmi): YaruTile: test LTR & RTL layout (#236)
- [J-P Nurmi](https://github.com/jpnurmi): YaruRow: drop Row-specific properties and rename to YaruTile (#235)
- [J-P Nurmi](https://github.com/jpnurmi): Yaru*Row: remove the width property (#234)
- [J-P Nurmi](https://github.com/jpnurmi): YaruRow: rename child properties to match ListTile (#233)
- [J-P Nurmi](https://github.com/jpnurmi): YaruRow: make the description a widget (#232)
- [J-P Nurmi](https://github.com/jpnurmi): YaruRow: enable by default (#231)
- [Paul Kepinski](https://github.com/Jupi007): Extract page controller from carousel (#228)
- [J-P Nurmi](https://github.com/jpnurmi): Replace YaruColorPickerButton with YaruOptionButton.color() (#226)
- [J-P Nurmi](https://github.com/jpnurmi): Carousel example: replace YaruRow with ButtonBar (#224)
- [J-P Nurmi](https://github.com/jpnurmi): Remove YaruSafeImage (#223)
- [J-P Nurmi](https://github.com/jpnurmi): YaruBanner: remove fallback icon / safe network image (#222)
- [J-P Nurmi](https://github.com/jpnurmi): rm -r linux/ (#221)
- [J-P Nurmi](https://github.com/jpnurmi): Implement Yaru(Round)IconButton as IconButton (#219)
- [J-P Nurmi](https://github.com/jpnurmi): Use super parameters (#218)
- [J-P Nurmi](https://github.com/jpnurmi): YaruOptionButton: replace iconData with a child widget (#217)
- [Frederik Feichtmeier](https://github.com/Feichtmeier): Layouts: add onTap callback (#216)

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@Jupi007 @jpnurmi 

Uploading... (4.9s)
The SDK constraint allows Dart 3.0.0, this is not allowed because Dart 3 does not exist.

Does this mean I need to reduce sdk version to 3.0.0 ?

**Comment by Jupi007** [comment]
I think the version number should be like <=2.99.0

**Comment by jpnurmi** [comment]
there's a confusion between Dart and Flutter SDK versions. "sdk" is the Dart SDK version vs. "flutter" is the Flutter SDK version. use the same constraints as yaru.dart uses?

```diff
diff --git a/pubspec.yaml b/pubspec.yaml
index da78276..75fade7 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -5,8 +5,8 @@ homepage: https://github.com/ubuntu/yaru_widgets.dart
 version: 1.1.5
 
 environment:
-  sdk: ">=2.17.0 <3.3.2"
-  flutter: ">=3.3.2"
+  sdk: ">=2.17.0 <3.0.0"
+  flutter: ">=3.3.0"
 
 dependencies:
   flutter:
```

**Comment by Jupi007** [comment]
Ah yes, <3.0.0 is better 👍

**Comment by Feichtmeier** [comment]
Thanks @jpnurmi - builds locally as before and the upload worked! :)

**Pull request merged**
