### PR TITLE
YaruMasterDetailPage: add golden test

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Comment by jpnurmi** [comment]
Any idea why the dividers are acting weird? :upside_down_face:  

image
image

**Comment by Feichtmeier** [comment]
Where are those images from?

**Comment by Jupi007** [comment]
I have no idea honestly...
We also have this issue about separators #305

**Comment by jpnurmi** [comment]
These are "screenshots" taken while running flutter test.

**Comment by jpnurmi** [comment]
With https://github.com/ubuntu/yaru.dart/pull/217 they'll become:

yaru_master_detail-page-landscape-dark
yaru_master_detail-page-landscape-light

**Comment by jpnurmi** [comment]
This is ready to go. Tests are passing after yaru.dart 0.4.3 was published.

**Pull request merged**
