### PR TITLE
Master-detail: use the new page transitions in yaru.dart

### PR DESCRIPTION
**Pull request by jpnurmi**
Vertical [page transitions](https://github.com/ubuntu/yaru.dart/pull/206) in landscape mode vs. horizontal in portrait:

https://user-images.githubusercontent.com/140617/190850908-b2e530ba-4f29-45bd-aa49-9890793dbfbd.mp4

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you ☺️

**Comment by jpnurmi** [comment]
Hmm, do we need a way to disable or override the transitions?

**Comment by Feichtmeier** [comment]
Currently not I think this is a very good solution for both small and big windows

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/190855735-dabb6afd-e2c8-441c-aaa4-fbe42550635d.mp4

Tested, looking good :+1: 

The dependency on yaru is not perfect, but currently I don't think anyone would use this lib here without yaru

**Comment by Jupi007** [comment]
> The dependency on yaru is not perfect, but currently I don't think anyone would use this lib here without yaru

I had the same thought :)

**Pull request merged**
