### PR TITLE
Add Tooltips (and so Semantics) to layouts navigation

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2022-10-06 20-17-00
Capture d’écran du 2022-10-06 20-17-16

This is useful when labels are elided (and it also add Semantics data);

### CODE REVIEW

**Comment by jpnurmi** [comment]
Could we consider replacing `iconBuilder` and `titleBuilder` with a `tileBuilder` and offer the recommended tile widget as a separate building block? This way, users could wrap it with anything or even replace the whole thing with something else.

Before:
```dart
YaruPageItem(
  iconBuilder: (_) => Icon(Icons.foo),
  titleBuilder: (_) => Text('bar'),
)
```

After:
```dart
YaruPageItem(
  tileBuilder: (_) => YaruPageTile(
    icon: Icon(Icons.foo),
    title: Text('bar'),
  ),
)
```

**Comment by Feichtmeier** [comment]
Sounds good - but how would we do the selection index then?

**Comment by jpnurmi** [comment]
Could we handle clicks below so that it works automatically as long as the supplied tile is non-interactive like `Yaru(Page)Tile` is? If you'd supply an interactive tile that blocks clicks, you'd have to rebuild the page yourself (`YaruMasterDetailPage` constructor should take the current index). Would that work?

**Comment by Feichtmeier** [comment]
I am unable to imagine this currently 😄 
I think if Paul agrees and you are sure that it would work paul cancels this PR and you create a new one?

**Comment by jpnurmi** [comment]
I'm 110% _unsure_ if it works. :rofl: I'm just brainstorming ideas to make it more open because we would like more control over the tile layout and contents in the firmware updater.

**Comment by Feichtmeier** [comment]
Currently both layouts build their tiles with the title and icon information
I don't know how we would do this when we forward our own tile
Eventually we could rather forward more builders like subtitle widget, tooltip string and so on
Then both layouts can keep the way they build their tiles

**Comment by Jupi007** [comment]
Imo, it is a really good idea :)
But if we go in this way, I don't know if we'll still be able to switch between layouts as simple as we do in the example.

Maybe still merge this PR?
_After I fix those conflicts 😅_

**Comment by jpnurmi** [comment]
> I don't know if we'll still be able to switch between layouts as simple as we do in the example.

True, it's a compromise between convenience vs. flexibility. :)

Even though, is it actually a common use case to switch between the master-detail and navi-rail layouts in a real app? Perhaps the two could be even different examples because the "Layout" item doesn't quite seem to fit with the other YaruXxx items. :)

**Comment by Feichtmeier** [comment]
Yes, the MD page is for very long lists
CL is for 3-10 I would say

**Comment by jpnurmi** [comment]
I hadn't actually noticed that the example had been changed to present the same page items in both layout modes. Nice! :wink:

**Comment by Jupi007** [comment]
About this PR, I think we should still add a Tooltip at least in `YaruNavigationRailItem`.
As labels can be hidden in this layout, it is imo important.
It can be also useful in `YaruMasterTile`.

**Comment by jpnurmi** [comment]
Sorry, I missed this. Sure, we could add a tooltip property at least to `YaruNavigationRailItem`! :+1:

`YaruMasterTile` can have multiple children so it's probably better to let users wrap the title & subtitle with separate Tooltip widgets.

image

**Comment by Jupi007** [comment]
I close this PR to redo another one.

**Pull request closed without merging**
