### PR TITLE
Analysis improvements and fixes

### PR DESCRIPTION
**Pull request by Feichtmeier**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Uh nice ty!

Was all easy to fix except:

prefer_null_aware_method_calls: true

for:
```dart
if (widget.onChange != null) {
  widget.onChange!(_isExpanded);
}
```

with 

```dart
final void Function(
    bool isExpanded,
  )?
```

**Comment by jpnurmi** [comment]
```dart
widget.onChange?.call(_isExpanded);
```

**Comment by jpnurmi** [comment]
I don't know why dart allows
```dart
widget.onChange!(_isExpanded);
```
but not
```dart
widget.onChange?(_isExpanded);
```
we have to add an explicit `.call()`...

**Comment by Feichtmeier** [comment]
Thanks! Was not aware of this way of calling methods!

**Pull request merged**
