### PR TITLE
Remove YaruPageItemTitle

### PR DESCRIPTION
**Pull request by jpnurmi**
The type of the immediate child should not matter. It could be wrapped into a non-Text widget. Just wrap with DefaultTextStyle and let any descendant Text inherit the style. If desired, users can override the defaults in builders.

> Many Widgets take a `child`. Widgets should be entirely agnostic about the type of that child. Don’t use `is` or similar checks to act differently based on the type of the child.

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-interleaving-multiple-concepts-together

Fixes: #271

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Did this change anything with the compact layout? I think this is the reason @Jupi007 introduced this, to have the text styled correctly there

**Comment by Jupi007** [comment]
Looking at the code, the text styling is still applied in both compact and master details layouts, so it is fine. It is just now forced.

In fact, I was thinking to make those defauts styles optional, because they are very specifics, especially in the compact layout.
If you want to replace the tile, maybe you don't want to overwrite again the text styling.
But maybe I was wrong, I don't know :)

**Comment by jpnurmi** [comment]
It's not forced but made the default. :) Do you want to add it to the theme? (still missing for CL)

**Comment by Feichtmeier** [comment]
So wrapping it yet in another default text style will overwrite the one beneath? Then it sounds fine

**Comment by jpnurmi** [comment]
`DefaultTextStyle` is great for propagating the desired defaults down the tree when not creating the `Text` yourself. In the builder, one can pass `maxLines`/`overflow`/`style` directly to `Text` constructor.

**Comment by jpnurmi** [comment]
Let's put this on hold until we have made the Compact Layout themable.

**Comment by Jupi007** [comment]
About the `is` thing (I want to justify myself a little 😇):
We first only had the master-details layout, and so I putted the `DefaultTextStyle` inside an optional but recommended `YaruPageItemTitle` widget. Then comes the compact layout, with different style requirements, but using the same data model classes as master-details (and so with `YaruPageItemTitle`). As we wanted to have the possibility to switch between both layouts, I only see the solution of moving the `DefaultTextStyle` inside the layouts themself, but make it conditionally to the `YaruPageItemTitle` widget when used as label.
In retrospect, all this is a bit kind of non sense 😅

Btw, talking about the compact layout, we have this problem: #259
The only solution I found is:
```dart
var label = 'Mes applications';
// ...
label.replaceAll(' ', '\u00A0');
```
But makes this generic would require a widget which would wrap a `Text` one... which isn't pretty at all.
Unless what, apps will need to do the job by themself, but I don't think it is the solution either.

**Comment by jpnurmi** [comment]
While we could have something like `TextStyle titleStyle` in `YaruMasterDetailTheme` and `YaruCompactLayoutTheme`, I feel like the "item" and "tile" builders are already powerful enough for overriding the default text style. Also, having a "title style" on the page theme level kinda goes against the idea of having arbitrary "item" and "tile" builders that may not necessarily even contain anything called "title". What do you think?

**Review by Jupi007 — APPROVED** [review]
I think you're right :)
LGFM so 👍

**Pull request merged**
