### PR TITLE
Ubuntu logo and example fix

### PR DESCRIPTION
**Pull request by ItzSwirlz**
Fingers crossed.

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
It obviously does not work.. thing is I'm not an expert with CustomPainter, nor the Ubuntu Logo so it would have to be constructed ground up.

**Comment by Feichtmeier** [comment]
@ItzSwirlz which one of your two PRs is the one you want to get merged?

@mivoligo I saw you working on a logo, too - maybe you two could join forces to finish the new Ubuntu logo widget? :smile_cat:

**Comment by ItzSwirlz** [comment]
> @mivoligo I saw you working on a logo, too - maybe you two could join forces to finish the new Ubuntu logo widget? 😸

That'd be cool, I'm cheeks at Flutter and CustomPaint.

> @ItzSwirlz which one of your two PRs is the one you want to get merged?

I was doing what you suggested earlier (or someone) - a pr to fix the widget and another to addmore to it

**Comment by ItzSwirlz** [comment]
> Here's what I had so far:
> https://www.dartpad.dev/?id=6bf971ce9a1e0e81d54dc67114474cdc

That's pretty much good as is IMO, thanks for working around my busy schedule/dumbness with flutter, i honestly regret this and if you didn't work on that I would say to remove the widget entirely and force apps to include it in themselves.

Is this good for me to rebase PR and include?

**Comment by Feichtmeier** [comment]
> > Here's what I had so far:
> > https://www.dartpad.dev/?id=6bf971ce9a1e0e81d54dc67114474cdc
> 
> That's pretty much good as is IMO, thanks for working around my busy schedule/dumbness with flutter, i honestly regret this and if you didn't work on that I would say to remove the widget entirely and force apps to include it in themselves.
> 
> Is this good for me to rebase PR and include?

Just test the code in your local branch, make a screenshot and post it here please

**Comment by Feichtmeier** [comment]
No answer since two months, closing

**Pull request closed without merging**
