### PR TITLE
fix(YaruTitleBar): improve parameters

### PR DESCRIPTION
**Pull request by Feichtmeier**
- forward platform parameters to YaruWindowControl
- give the option to control padding and spacing from the constructor or the theme

grafik

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
LGTM 👍

**Comment by Feichtmeier** [comment]
important note to us
when you run the golden tests from windows, all are changed to windows ^^  but this is a rare case I hope

**Comment by Feichtmeier** [comment]
@Jupi007 could you check if I made any mistake on your UBuntu machine?

**Review by Jupi007 — CHANGES_REQUESTED** [review]
> when you run the golden tests from windows, all are changed to windows

Oh okay, well can you add a golden variant for the title bar test so we can test both yaru/windows?
I did it for the window controls test.

**Comment by Feichtmeier** [comment]
> Oh okay, well can you add a golden variant for the title bar test so we can test both yaru/windows?

you mean I should commit the test changes? dont they overwrite anything?=

**Comment by Jupi007** [comment]
No no, I didn't mean to commit and overwrite the yaru images with windows ones, but to add a windows golden variants to append the windows variant to the yaru images 🙂

I just tested your branch on Ubuntu and I can't notice any problem.

**Comment by Feichtmeier** [comment]
> No no, I didn't mean to commit and overwrite the yaru images with windows ones, but to add a windows golden variants to append the windows variant to the yaru images 🙂
> 
> I just tested your branch on Ubuntu and I can't notice any problem.
> 
> As you can see here, I added both variants to the test suit:
> 
> https://github.com/ubuntu/yaru_widgets.dart/blob/5a05b25e0797cd765e2c9589766486c3eb8201f8/test/widgets/yaru_window_control_test.dart#L89

oh no. how would I do this? :D where?

**Comment by Jupi007** [comment]
Here:

https://github.com/ubuntu/yaru_widgets.dart/blob/5a05b25e0797cd765e2c9589766486c3eb8201f8/test/widgets/yaru_title_bar_test.dart#L144-L212

You can do something similar as I did here:

https://github.com/ubuntu/yaru_widgets.dart/blob/5a05b25e0797cd765e2c9589766486c3eb8201f8/test/widgets/yaru_window_control_test.dart#L51-L57

https://github.com/ubuntu/yaru_widgets.dart/blob/5a05b25e0797cd765e2c9589766486c3eb8201f8/test/widgets/yaru_window_control_test.dart#L92-L93

Or if you want, I can do it in a separate PR 🙂

**Comment by Feichtmeier** [comment]
Yes please do it

**Review by Jupi007 — APPROVED** [review]
Okay, so let's merge this 👍
I'll update the tests in another PR.

**Pull request merged**
