### PR TITLE
Check/Radio/Switch/Button/ListTile: allow customizing mouse cursor

### PR DESCRIPTION
**Pull request by jpnurmi**
- https://github.com/canonical/ubuntu-desktop-installer/issues/1532

Ref: ubuntu/yaru.dart#85

### CODE REVIEW

**Review by Jupi007 — CHANGES_REQUESTED** [review]
This seems to looks good :)
But can you also add the `mouseCursor` property to checkbox/radio/switch/togglable theme classes?

**Edit:** I suppose you also plan a PR to change the default cursor?

**Comment by jpnurmi** [comment]
> But can you also add the `mouseCursor` property to checkbox/radio/switch/togglable theme classes?

Thanks, done!

> **Edit:** I suppose you also plan a PR to change the default cursor?

It's a different discussion but let's start by making them customizable from the outside, at least. :)

I used to feel pretty strong against the hand cursors which is why I spent so much time contributing changes to Flutter to make it themable. The problem is that there are a) many legacy widgets that are missing themes altogether or cannot be made themable without breaking things and b) there are new widgets coming up in every release that are missing themable mouse cursors. As a result, you may end up with a strange mix where some widgets have hand and some basic cursors, and you might have to finish it off by applying some hacks on the app side. Therefore it might be hard to make it the default until Flutter offers a clean way to change the clickable cursor everywhere.

**Review by Jupi007 — APPROVED** [review]
LGTM 👍

**Comment by Jupi007** [comment]
I understand.
But to be very honest, now I pretty much like the usage of the pointer cursor in clickable area 😅
It adds an additional semantic information.

**Pull request merged**
