### PR TITLE
Extract YaruWatermark from YaruBanner

### PR DESCRIPTION
**Pull request by jpnurmi**
### Before:
```dart
YaruBanner(
  watermarkIcon: ...
  ...
),
```
### After:
```dart
YaruWatermark(
  watermark: ...
  child: YaruBannerOrAnythingElse(
    ...
  ),
),
```
Screenshot from 2022-11-29 23-01-16

### CODE REVIEW

**Comment by Feichtmeier** [comment]
? why?

**Comment by jpnurmi** [comment]
After this, we'd be only a few steps away from
```dart
YaruBanner(
  child: YaruTile(
    ...
  ),
)
```
vs.
```dart
YaruBanner(
  child: Column(
    children: [
      Icon(...),
      Text(...),
    ]
  ),
)
```

**Comment by jpnurmi** [comment]
Frankly speaking, the watermark feature feels a bit store-centric but perhaps there will be other use cases? With this, you can at least control the positioning and translucency. :wink:

**Comment by Feichtmeier** [comment]
Ironically it is currently not used in the store, but I could imagine it can be useful anywhere. Generally it is nice to have a brouder set of components to chose from . If it helps you with the workshop app we can merge this, but generally it is always this configuration vs convient question :P 

Are you sure the stack always has the same size as the child you add to watermark?

**Pull request merged**
