### PR TITLE
fix: reduce number of used scaffolds

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

Ref #728

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Since the YMD changed, the golden tests for those widgets changed. Even though the visual look does not change but the layers of widgets. 
Since my host is on 3.16 I can not properly push updated goldens
Any idea how we could fix this @Jupi007 @d-loose ? Except, me using different flutter versions :S

**Comment by Jupi007** [comment]
What we can do is setup a github action for this 🤔

**Comment by Feichtmeier** [comment]
We have

https://github.com/ubuntu/yaru_widgets.dart/blob/main/.github/workflows/nightly.yml

but it is flutter 3.10 xD

**Comment by Feichtmeier** [comment]
@Jupi007 
since very precisely YMD goldens do not match anymore
```
❌ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: landscape-light: themeMode: ThemeMode.light, value: Instance of 'YaruMasterDetailGoldenVariant') (failed)
❌ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: landscape-dark: themeMode: ThemeMode.dark, value: Instance of 'YaruMasterDetailGoldenVariant') (failed)
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: portrait-subtitle-light: themeMode: ThemeMode.light, value: Instance of 'YaruMasterDetailGoldenVariant')
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: portrait-subtitle-dark: themeMode: ThemeMode.dark, value: Instance of 'YaruMasterDetailGoldenVariant')
❌ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: landscape-subtitle-light: themeMode: ThemeMode.light, value: Instance of 'YaruMasterDetailGoldenVariant') (failed)
❌ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: landscape-subtitle-dark: themeMode: ThemeMode.dark, value: Instance of 'YaruMasterDetailGoldenVariant') (failed)
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: portrait-spacer-light: themeMode: ThemeMode.light, value: Instance of 'YaruMasterDetailGoldenVariant')
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: portrait-spacer-dark: themeMode: ThemeMode.dark, value: Instance of 'YaruMasterDetailGoldenVariant')
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_linear_progress_indicator_test.dart: - YaruLinearProgressIndicator Test
✅ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_linear_progress_indicator_test.dart: golden images (variant: indeterminate-light: themeMode: ThemeMode.light, value: null)
❌ /home/runner/work/yaru_widgets.dart/yaru_widgets.dart/test/widgets/yaru_master_detail_page_test.dart: golden images (variant: landscape-spacer-light: themeMode: ThemeMode.light, value: Instance of 'YaruMasterDetailGoldenVariant') (failed)
```
could we merge this one and then regen them tonight with the CI? (at least I think this should work)

**Review by Jupi007 — APPROVED** [review]
Great, LGTM :+1:

**Comment by Feichtmeier** [comment]
Okay let's hope this plan works :D 🤞 
Otherwise we can still revert this

**Pull request merged**
