### PR TITLE
Add `YaruMasterDetailPage.orientationOf()` and `appBarBuilder`

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
Very cool, LGFM :+1: 

_you just need to fix a missing comma_

**Comment by jpnurmi** [comment]
@Feichtmeier does this help with the back button issue? i have a feeling it doesn't because if `Navigator.of(context).canPop()` didn't work for you, it sounds like you're building the title bar outside the master-detail page so you can't access the orientation either via an inherited widget like this either?

**Comment by Feichtmeier** [comment]
ah you mean because

```dart
return Column(
      children: [
        appBar,
        Expanded(
          child: YaruMasterDetailPage(
          ```
          
          ?
          
          Well i don't know how to get this layout otherwise. Should I wrap it in a scaffold?

**Comment by jpnurmi** [comment]
I'm still trying to understand the requirements. :)

The original question was how to query MD orientation and this PR adds that mechanism but I'm afraid it's not possible to access an inherited widget from where you'd like to, above the master detail page.

We could make it possible to query the current orientation from the controller, though.

```dart
class YaruMasterDetailController extends YaruPageController {
  Orientation get orientation => ...
}
```

**Comment by Feichtmeier** [comment]
> I'm still trying to understand the requirements. :)
> 
> The original question was how to query MD orientation and this PR adds that mechanism but I'm afraid it's not possible to access an inherited widget from where you'd like to, above the master detail page.
> 
> We could make it possible to query the current orientation from the controller, though.
> 
> ```dart
> class YaruMasterDetailController extends YaruPageController {
>   Orientation get orientation => ...
> }
> ```

Sounds enough for my case. But is this layout really so weird? 😄 Alternatively I could maybe wrap it in a scaffold?

**Comment by jpnurmi** [comment]
It's not the layout being weird or you doing anything wrong. We definitely want to support the layout you have. It's just impossible in Flutter to access an _inherited_ widget from the context above so we need to make it possible to get the information in some other way.

```dart
Scaffold(
  appBar: YaruWindowTitleBar(
    // context OUTSIDE YaruMasterDetailPage
    // - Navigator.of(context) finds the ROOT navigator, not the MD navigator
    // - YaruMasterDetailPage.of(context) doesn't find anything
  ),
  body: YaruMasterDetailPage(
    pageBuilder: (context, index) {
      // context INSIDE YaruMasterDetailPage
      // - Navigator.of(context) finds the MD navigator
      // - YaruMasterDetailPage.of(context) is OK
    },
  ),
)
```

**Comment by Feichtmeier** [comment]
ah right! 
I test this PR now

**Comment by Feichtmeier** [comment]
> @Feichtmeier does this help with the back button issue? i have a feeling it doesn't because if `Navigator.of(context).canPop()` didn't work for you, it sounds like you're building the title bar outside the master-detail page so you can't query the MD orientation via an inherited widget like this either?

confirming. as the element is not reachable from down there 
Thanks for trying though! If this is still an improvement you can ofc still merge as you like

**Comment by jpnurmi** [comment]
@Jupi007 @Feichtmeier do we have any use case for this?

**Comment by Jupi007** [comment]
Imo, this can be useful in some situations.
Ex: I you want to make something different in the detail view depending on the layout.

**Comment by jpnurmi** [comment]
Thanks for chiming in. I started feeling somehow unsure because this didn't solve the original issue. :)

**Pull request merged**
