### PR TITLE
Add YaruAutocomplete

### PR DESCRIPTION
**Pull request by jpnurmi**
A Yarufied version of [Autocomplete](https://api.flutter.dev/flutter/material/Autocomplete-class.html):
- uses `YaruBorderContainer` and `MenuItemButton` to gain more Yaru-like looks
- using `MenuItemButton` makes it possible to customize the mouse cursor
- optionally, allows controlling the width of the popup

|       | Material | Yaru |
|-------|--------|-------|
| Light | image | image |
| Dark  | image | image |

Ref: https://github.com/canonical/ubuntu-desktop-installer/issues/1532

### CODE REVIEW

**Comment by jpnurmi** [comment]
Oh right, `YaruBorderContainer` doesn't have a default background! :smile: 

image

**Review by Feichtmeier — APPROVED** [review]
Very cool

**Comment by jpnurmi** [comment]
Is `ColorScheme.background` or `ColorScheme.surface` better background color for this type of menu-like popup?

**Review by Jupi007 — APPROVED** [review]
I can't test it for now, but it looks great!

About the background, I would say to use surface, so it stands out from the background.

**Comment by jpnurmi** [comment]
With this, we could use the same color as menus have in yaru.dart:
- https://github.com/ubuntu/yaru.dart/pull/313

**Comment by jpnurmi** [comment]
Looks better now

| Light | Dark |
|---|---|
|  |  |

**Pull request merged**
