### PR TITLE
Add support for high contrast theme

### PR DESCRIPTION
**Pull request by d-loose**
Adds high contrast borders to
- `YaruTitleBar`
- `YaruWindowControl`
- `YaruMasterTile`

image

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
Great, thanks @d-loose 

LGTM :+1:

**Comment by jpnurmi** [comment]
Thanks, @d-loose! Any concerns with this approach @Feichtmeier and @Jupi007? Unlike me earlier attempt with "barely noticeable" borders, this keeps the normal themes untouched.

**Review by Feichtmeier — APPROVED** [review]
Since it doesn't affect the normal themes it's ok

**Comment by Jupi007** [comment]
I just have one note: is adding a border change the size of the window controls?

**Comment by Feichtmeier** [comment]
> I just have one note: is adding a border change the size of the window controls?

that would be bad :thinking:

**Comment by jpnurmi** [comment]
@Jupi007 good catch!

**Comment by d-loose** [comment]
Learned about `strokeAlign` :)

| | Dark | Light |
| - | - | - |
| Normal | image | image |
| High Contrast | image | image |

**Review by Jupi007 — APPROVED** [review]
Great, thanks @d-loose 

I didn't know this `strokeAlign` property

**Review by Feichtmeier — APPROVED** [review]
[Bildschirmaufzeichnung vom 24.03.2023, 11:00:04.webm](https://user-images.githubusercontent.com/15329494/227490605-916ddbce-de2e-4ebe-8550-b6b463511566.webm)

can't see any visual regression

**Pull request merged**
