### PR TITLE
[WIP]  Add more to the Ubuntu logo widget

### PR DESCRIPTION
**Pull request by ItzSwirlz**
I really jumped the gun. We are missing.. a lot. I'm at school, so I can't do work but I'm opening this now so I see it later.

There should be an option for

- [ ] Showing logo regularly - circle of friends
- [ ] Showing the ubuntu circle of friends with the 'banner' (rectangular thing)
- [ ] Showing the ubuntu circle of friends with text
- [ ] Showing the ubuntu circle of friends with text in a banner
- [ ] Showing the entire ubuntu logo horizontally and vertically
- [ ] Being able to colorize and switch to different flavors

After watching the FlutterLogo widget of the week, which I knew the existance of FlutterLogo (which inspired this widget in the first place), there is a lot more I can add. So let's do it!

**ATM: this PR is just the previous one without changes until I commit and force-push**

### CODE REVIEW

**Comment by ItzSwirlz** [comment]
> What would you say about creating it using CustomPainter instead of using an image?

That would be a better idea, however I'd have to learn it

**Comment by Feichtmeier** [comment]
@ItzSwirlz 

I really appreciate your contributions. However could you eventually increase the level of completeness of your PRs before you open them? It looks like you open a pull request and then expect me to finish it :laughing: 

Ontopic: I tried the current UbuntuLogo in yaru_widgets.dart master and it does not work:

image

**Comment by ItzSwirlz** [comment]
> I really appreciate your contributions. However could you eventually increase the level of completeness of your PRs before you open them? It looks like you open a pull request and then expect me to finish it 😆

No no no, they are *my* job. Marking period ends next week, and I'll be on spring break to finish. This is a self-reminder.



> Ontopic: I tried the current UbuntuLogo in yaru_widgets.dart master and it does not work:

I am going to shove that error up my-okay lets go with the custom painter.

**Comment by Feichtmeier** [comment]
> > I really appreciate your contributions. However could you eventually increase the level of completeness of your PRs before you open them? It looks like you open a pull request and then expect me to finish it laughing
> 
> No no no, they are _my_ job. Marking period ends next week, and I'll be on spring break to finish. This is a self-reminder.
> 
> > Ontopic: I tried the current UbuntuLogo in yaru_widgets.dart master and it does not work:
> 
> I am going to shove that error up my-okay lets go with the custom painter.

Ok cool!
Could you eventually make a second PR where you only commit a fix for the logo to work?
Then you could include this commit in this PR and end up with two PRs instead of one, and I can already use the logo in the settings app in the time you add the other stuff? :)

**Comment by ItzSwirlz** [comment]
> Then you could include this commit in this PR and end up with two PRs instead of one, and I can already use the logo in the settings app in the time you add the other stuff? :)

Sure!

I just gave a quick stab at the CustomPainter and based on a Flutter video there is a deal with having images but I was having linter issues, so I decided I would come back to it another time (like tomorrow, I have the week off from school) but again linking to an AssetImage could result in the same error message. Maybe that figma to flutter thing has custom painter, idk

**Comment by ItzSwirlz** [comment]
@Feichtmeier ugh, here's what I'm dealing with. I'm using this video and I get this

```
The argument type 'Image (where Image is defined in /home/jpeisach/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/image.dart)' can't be assigned to the parameter type 'Image (where Image is defined in /home/jpeisach/snap/flutter/common/flutter/bin/cache/pkg/sky_engine/lib/ui/painting.dart)'. (Documentation) 
Image is defined in /home/jpeisach/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/image.dart (image.dart:35).
Image is defined in /home/jpeisach/snap/flutter/common/flutter/bin/cache/pkg/sky_engine/lib/ui/painting.dart (painting.dart:35).
```

https://www.youtube.com/watch?v=vvI_NUXK00s

It seems that its confusing dart's ui.Image and flutter's image class.. what else shoudl i do

**Comment by mivoligo** [comment]
I'd say you don't need Image at all to create the logo in CustomPainter. Just paths and shapes.

**Comment by ItzSwirlz** [comment]
> I'd say you don't need Image at all to create the logo in CustomPainter. Just paths and shapes.

I just rammed it with Image.file. #114

**Comment by Feichtmeier** [comment]
@ItzSwirlz can I fix the logo and you close your two PRs?

**Comment by ItzSwirlz** [comment]
> I just realized the ubuntu logo is already in yaru_icons.dart
> 
> [ubuntu-flutter-community/settings#334 (comment)](https://github.com/ubuntu-flutter-community/settings/pull/334#issuecomment-1163556300)
> 
> So I think the logo in yaru widgets is not really needed anymore or could be created via the funny stack I've added here: https://github.com/ubuntu-flutter-community/settings/blob/78660d0e61695b2087420900972062ef09475457/lib/view/pages/info/info_page.dart#L75


Wow.. I didn't even realize that worked.

> @ItzSwirlz can I fix the logo and you close your two PRs?

Whatever you want; I can fix it if you so wish with this suggestion or aforementioned. I'm pretty much done contributing stuff I can never be 100% sure what I am doing is somewhat safe and good.

My idea was to make it easier for the logo to overall be colored or adjusted; but I guess that can be done later

Honestly I'm pissed I keep letting everyone down. Currently my focus at the moment is Cinnamon 5.4.0 in debian/ubuntu kinetic and other CVEs.. literally anything to get my PPU application going

**Comment by Feichtmeier** [comment]
You don't let everyone down. XD
You should eventually just be sure that you have a working dev environment before opening the PR
Yes let's just close this here, I think we don't need an Ubuntu logo in this repo as we have the logo as an icon in yaruiconsdart

**Comment by Feichtmeier** [comment]
No answer since two months, closing

**Pull request closed without merging**
