### PR TITLE
Add YaruRadio

### LINKED ISSUE #353: Add YaruRadio

### PR DESCRIPTION
**Pull request by Jupi007**
- [x] Extract generic togglable stuff ;
- [x] Add YaruRadio ;
- [x] Add and adapt Golden tests ;
- [x] Add functional tests.

**Untoggleable:**

https://user-images.githubusercontent.com/36476595/199790187-be83afab-ddb2-4caf-95ee-23e209422775.mp4

**Toggleable:**

https://user-images.githubusercontent.com/36476595/199790182-d9d90924-b0fc-461f-a61c-1889026d9ce4.mp4

**With disabled state:**

https://user-images.githubusercontent.com/36476595/199790164-875dadc6-60b8-4e43-b349-41cb4d992a55.mp4

Closes #353

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looks also very nice!

just that I become more and more unsure about the size change for this and the checkbox

@madsrh @jpnurmi WDYT?

**Comment by madsrh** [comment]
Looks great 👍

**Comment by Jupi007** [comment]
> just that I become more and more unsure about the size change for this and the checkbox

I finally think you're right. With the previous checkmark, the larger size (22px) was better, but now we use an even checkmark, 20px is also fine.

**22px:**

image

**20px:**

Capture d’écran du 2022-11-03 21-05-09

**Comment by Jupi007** [comment]
Some other screenshots:

### CheckButton

**22px**

Capture d’écran du 2022-11-03 21-13-33

**20px**

Capture d’écran du 2022-11-03 21-13-48

### RadioButton

**22px**

Capture d’écran du 2022-11-03 21-13-38

**20px**

Capture d’écran du 2022-11-03 21-13-54

**Review by Feichtmeier — APPROVED** [review]

**Comment by Jupi007** [comment]
Fine, let's go with the switch now :)

**Pull request merged**
