### PR TITLE
Better project folders

### PR DESCRIPTION
**Pull request by Jupi007**
The project started to be a bit messy, so I propose to create the following folders :

- `/layout/master_detail`
- `/layout/compact`
- `/controls/progess_indicator` (splited `yaru_progress_indicator` fat file)
- `/controls/togglable`
- `/controls/toggle_button`

## Pull request checklist

- [x] This PR does not introduce visual changes

Redo of #406

### CODE REVIEW

**Comment by jpnurmi** [comment]
I'd actually prefer less hierarchy to avoid unaesthetic "../../foo/bar.dart" kind of imports... :)

**Comment by Jupi007** [comment]
I understand :)

But I would still like to split `yaru_progress_indicator.dart` which is really too big, if you agree.

**Comment by jpnurmi** [comment]
Sure, :+1  for smaller files! :slightly_smiling_face:

**Comment by Jupi007** [comment]
Okay, so I close this PR to open a new one 🙂

**Pull request closed without merging**
