### PR TITLE
Feat/example (#2)

### PR DESCRIPTION
**Pull request by shan-shaji**
- [x]  Add `YaruRow` example
- [x]  Add `ImageTile` Example
- [x] Add `YAruExtraOptionRow` example
- [x] Add `YaruOptionButton` example
- [x]  Add `YaruOptionCard` example
- [x] Add `YaruPageContainer` example
- [x] Add `YaruRow` example
- [x] Add `YaruSearchAppBar` example
- [x] Add `YaruSection` example
- [x] Add `YaruSingleInfoRow` example
- [x] Add `YaruSliderRow` example
- [x] Add `YaruSliderSecondary` example
- [x] Add `YaruSwitchRow` example
- [x] Add `YaruToggleButtonsRow` example

### CODE REVIEW

**Comment by shan-shaji** [comment]
Hey @Feichtmeier, I have added some examples, Do check when you have time

**Comment by Feichtmeier** [comment]
Wow @shan-shaji thank you very much!
Totally going to merge this nice example change. 
Just one question: are those empty checkboxes infront of the list tile descriptions intended?
grafik

**Comment by shan-shaji** [comment]
Just added to look like a bullet point. If not needed I will remove it

**Comment by Jupi007** [comment]
What about use random icons (so it looks like a "real" app)?

**Comment by shan-shaji** [comment]
yes that would be nice, i will add random yaru icons

**Comment by Feichtmeier** [comment]
Sounds like a nice idea :)

**Comment by shan-shaji** [comment]
Hey @Feichtmeier I have added random emoji icons, do check

**Comment by Feichtmeier** [comment]
Thanks :)

image

Merging, maybe some day we could have an icon for each widget

**Comment by Jupi007** [comment]
It looks very good :+1:

**Pull request merged**
