### PR TITLE
Add YaruSimpleDialog widget

### LINKED ISSUE #28: Create a YaruSimpleDialog widget

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2021-12-20 14-09-20
Capture d’écran du 2021-12-20 14-09-54

Closes #28
See https://github.com/Feichtmeier/settings/issues/209

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Cool thanks!

Could the close button be a little bit moved so it's more in the right corner?

**Comment by Jupi007** [comment]
Like this?

Capture d’écran du 2021-12-20 15-29-07

**Comment by Feichtmeier** [comment]
Yes :)

**Comment by Jupi007** [comment]
Done:

Capture d’écran du 2021-12-20 15-51-44
Capture d’écran du 2021-12-20 15-52-11

**Review by Feichtmeier — APPROVED** [review]

**Comment by Feichtmeier** [comment]
Now it needs to be "only" included in some dialogs :D 
Interested? ;D

**Comment by Jupi007** [comment]
Ofc :D

Have I enough accreditations to publish a new release to pub.dev?

**Comment by Jupi007** [comment]
Oh wait, I don't need to publish a new release as your settings app use the git version 😅

**Pull request merged**
