### PR TITLE
Add comments on new controls widgets

### LINKED ISSUE #374: Add comments on new controls widgets

### PR DESCRIPTION
**Pull request by Jupi007**
I mostly reused material controls comments.

Fixes #374

## Pull request checklist

- [x] Either this PR does not introduce visual changes.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Pretty hard to review the comments apart from typos though :) Imo, if you think you've written them as you intended the widgets to be, merge it.

**Comment by Jupi007** [comment]
Okay :+1: 
If you see any typo, I think it is ok to merge :)

**Comment by Feichtmeier** [comment]
No didnt see, but there is a great addon 
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
if you are unsure

**Comment by Jupi007** [comment]
Thanks @Feichtmeier, that ext is very useful.
I didn't noticed any typo, so let's merge :)

**Pull request merged**
