### PR TITLE
Example: make better use of YaruWindowTitleBar

### PR DESCRIPTION
**Pull request by jpnurmi**
image
image
image
image

Supercedes #513

### CODE REVIEW

**Comment by jpnurmi** [comment]
There's one special page that doesn't play nicely:

image
image

**Comment by Feichtmeier** [comment]
Yes it has an AppBar instead of a yaru bar

https://github.com/ubuntu/yaru_widgets.dart/blob/main/example/lib/pages/navigation_page.dart#L26

**Comment by jpnurmi** [comment]
Damn, the idea of using a divided title bar with master-detail and shared one navi-rail doesn't work then. 🤔

**Comment by jpnurmi** [comment]
What if we make the nested pages use YaruWindowTitleBar and filter out the whole page item from navi-rail?

| MD | NR |
|---|---|
| image | image |

**Comment by Feichtmeier** [comment]
> Damn, the idea of using a divided title bar with master-detail and shared one navi-rail doesn't work then. thinking

Well we had a version of the layouts which needed those titlebuilders for the appbar in the scaffolds. Pro was that we did not use so many scaffolds then. But if we would do this again we would need one more builder for the appbar title because we are using the titlebuilders for the master tiles and navi items now

**Comment by Feichtmeier** [comment]
> What if we make the nested pages use YaruWindowTitleBar and filter out the whole page item from navi-rail?

I didn't understand this :thinking: could you elaborate ?

**Comment by jpnurmi** [comment]
Proposal:
```dart
  PageItem(
    title: 'YaruNavigationPage',
    iconBuilder: (context, selected) => selected
        ? const Icon(YaruIcons.compass_filled)
        : const Icon(YaruIcons.compass),
    pageBuilder: (_) => const NavigationPage(),
    supportedLayouts: {YaruMasterDetailPage}, // <=== added (defaults to {YaruMasterDetailPage,YaruNavigationPage})
  ),
```

**Comment by Feichtmeier** [comment]
> Proposal:
> 
> ```dart
>   PageItem(
>     title: 'YaruNavigationPage',
>     iconBuilder: (context, selected) => selected
>         ? const Icon(YaruIcons.compass_filled)
>         : const Icon(YaruIcons.compass),
>     pageBuilder: (_) => const NavigationPage(),
>     supportedLayouts: {YaruMasterDetailPage}, // <=== added (defaults to {YaruMasterDetailPage,YaruNavigationPage})
>   ),
> ```

ahhhh! :) 

Yeah maybe this is a good idea. Eventually we could add more layouts in the future with fixed appbars which require title widgets plus nullable leading widgets

**Comment by jpnurmi** [comment]
> Eventually we could add more layouts in the future with fixed appbars which require title widgets plus nullable leading widgets

Yaru wizard would be cool. :) I've learned with the installer that wizards can have awfully complicated conditional navigation rules, though.

**Pull request merged**
